<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class ProductionSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        // ── Cài đặt ──
        DB::table('admin_settings')->truncate();
        DB::table('admin_settings')->insert([
            ['key'=>'admin_password','value'=>'$2y$12$ATJTrazsdBuCzsdBH8zcku5yJkFLnXCXZ7L5.6yz2tAPEhnwXPsyK','created_at'=>$now,'updated_at'=>$now],
            ['key'=>'tg_token','value'=>'','created_at'=>$now,'updated_at'=>$now],
            ['key'=>'tg_chat_id','value'=>'','created_at'=>$now,'updated_at'=>$now],
            ['key'=>'bank_id','value'=>'MSB','created_at'=>$now,'updated_at'=>$now],
            ['key'=>'bank_acc','value'=>'13001011945010','created_at'=>$now,'updated_at'=>$now],
            ['key'=>'bank_name','value'=>'DOAN ANH TUAN','created_at'=>$now,'updated_at'=>$now],
            ['key'=>'bank_label','value'=>'TT DALI TRANH','created_at'=>$now,'updated_at'=>$now],
            ['key'=>'shop_phone','value'=>'0856.911.698','created_at'=>$now,'updated_at'=>$now],
            ['key'=>'shop_address','value'=>'Thôn Bắc Cường, Xã Minh Thái, Tỉnh Ninh Bình','created_at'=>$now,'updated_at'=>$now],
            ['key'=>'ga_id','value'=>'','created_at'=>$now,'updated_at'=>$now],
            ['key'=>'fb_pixel_id','value'=>'','created_at'=>$now,'updated_at'=>$now],
            ['key'=>'zalo_oa_id','value'=>'','created_at'=>$now,'updated_at'=>$now],
            ['key'=>'meta_title','value'=>'DALI – Tranh Tô Màu Số Hóa','created_at'=>$now,'updated_at'=>$now],
            ['key'=>'meta_description','value'=>'Bộ tranh tô màu số hóa DALI – ai cũng có thể tạo ra kiệt tác hội họa của riêng mình.','created_at'=>$now,'updated_at'=>$now],
            ['key'=>'meta_keywords','value'=>'tranh tô màu số hóa, paint by numbers, DALI tranh','created_at'=>$now,'updated_at'=>$now],
            ['key'=>'mail_from','value'=>'','created_at'=>$now,'updated_at'=>$now],
            ['key'=>'mail_name','value'=>'DALI Tranh Tô Màu','created_at'=>$now,'updated_at'=>$now],
            ['key'=>'free_ship_from','value'=>'299000','created_at'=>$now,'updated_at'=>$now],
            ['key'=>'ship_fee','value'=>'30000','created_at'=>$now,'updated_at'=>$now],
            ['key'=>'discount_bank','value'=>'10','created_at'=>$now,'updated_at'=>$now],
            ['key'=>'ghtk_token','value'=>'','created_at'=>$now,'updated_at'=>$now],
            ['key'=>'ghtk_shop_id','value'=>'','created_at'=>$now,'updated_at'=>$now],
            ['key'=>'ghtk_pick_address','value'=>'','created_at'=>$now,'updated_at'=>$now],
            ['key'=>'ghtk_pick_province','value'=>'Hà Nội','created_at'=>$now,'updated_at'=>$now],
            ['key'=>'ghtk_pick_district','value'=>'Hoàn Kiếm','created_at'=>$now,'updated_at'=>$now],
            ['key'=>'default_weight','value'=>'500','created_at'=>$now,'updated_at'=>$now],
            ['key'=>'vtp_token','value'=>'','created_at'=>$now,'updated_at'=>$now],
            ['key'=>'vtp_sender_phone','value'=>'','created_at'=>$now,'updated_at'=>$now],
            ['key'=>'vtp_sender_address','value'=>'','created_at'=>$now,'updated_at'=>$now],
            ['key'=>'zalo_link','value'=>'https://zalo.me/0856911698','created_at'=>$now,'updated_at'=>$now],
        ]);

        // ── Danh mục ──
        DB::table('categories')->truncate();
        DB::table('categories')->insert([
            ['id'=>1,'name'=>'Hoa & Thực vật','slug'=>'hoa-thuc-vat','description'=>'Tranh tô màu chủ đề các loài hoa và thực vật.','image'=>'categories/hoa.jpg','is_active'=>true,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>2,'name'=>'Phong cảnh','slug'=>'phong-canh','description'=>'Tranh tô màu phong cảnh thiên nhiên, núi non, biển cả.','image'=>'categories/phong-canh.jpg','is_active'=>true,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>3,'name'=>'Động vật','slug'=>'dong-vat','description'=>'Tranh tô màu chủ đề động vật dễ thương, ngộ nghĩnh.','image'=>'categories/dong-vat.jpg','is_active'=>true,'created_at'=>$now,'updated_at'=>$now],
        ]);

        // ── Kích thước & giá ──
        DB::table('sizes')->truncate();
        DB::table('sizes')->insert([
            ['id'=>1,'name'=>'20×20 cm','note'=>'','price'=>63000,'sort_order'=>1,'is_active'=>true,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>2,'name'=>'30×30 cm','note'=>'','price'=>88000,'sort_order'=>2,'is_active'=>true,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>3,'name'=>'30×37,5 cm','note'=>'','price'=>169000,'sort_order'=>3,'is_active'=>true,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>4,'name'=>'40×40 cm','note'=>'','price'=>179000,'sort_order'=>4,'is_active'=>true,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>5,'name'=>'40×50 cm','note'=>'','price'=>199000,'sort_order'=>5,'is_active'=>true,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>6,'name'=>'50×65 cm','note'=>'','price'=>299000,'sort_order'=>6,'is_active'=>true,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>7,'name'=>'60×75 cm','note'=>'không khung','price'=>399000,'sort_order'=>7,'is_active'=>true,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>8,'name'=>'70×90 cm','note'=>'không khung','price'=>459000,'sort_order'=>8,'is_active'=>true,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>9,'name'=>'80×90 cm','note'=>'không khung','price'=>599000,'sort_order'=>9,'is_active'=>true,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>10,'name'=>'40×80 cm','note'=>'panorama','price'=>359000,'sort_order'=>20,'is_active'=>true,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>11,'name'=>'50×100 cm','note'=>'panorama','price'=>469000,'sort_order'=>21,'is_active'=>true,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>12,'name'=>'60×120 cm','note'=>'panorama','price'=>629000,'sort_order'=>22,'is_active'=>true,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>13,'name'=>'70×140 cm','note'=>'panorama','price'=>829000,'sort_order'=>23,'is_active'=>true,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>14,'name'=>'80×160 cm','note'=>'panorama','price'=>1090000,'sort_order'=>24,'is_active'=>true,'created_at'=>$now,'updated_at'=>$now],
        ]);

        // ── Sản phẩm (103 tranh) ──
        DB::table('products')->truncate();
        DB::table('products')->insert([
            ['id'=>1,'category_id'=>1,'name'=>'Tranh Hoa Sen Hồng H091','slug'=>'tranh-hoa-sen-hong-6a19ab68d6c8c','description'=>'Tranh hoa sen hồng (mã H091) – biểu tượng tinh khiết, bình an. Khổ chuẩn 40×50cm, 24 màu. Có thể đặt khổ lớn hơn: 50×65, 60×75, 70×90, 80×100cm.','image'=>'','price'=>159000,'color_count'=>,'size_ids'=>'["3","5","6","7","8","9"]','is_active'=>true,'is_featured'=>false,'sort_order'=>1,'sold_count'=>2,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>2,'category_id'=>1,'name'=>'Tranh Hoa Hướng Dương H072','slug'=>'tranh-hoa-huong-duong-6a19ab68f2111','description'=>'Tranh hoa hướng dương rực rỡ (mã H072) – mang năng lượng tích cực. Khổ chuẩn 40×50cm, 24 màu.','image'=>'','price'=>159000,'color_count'=>,'size_ids'=>'["3","5","6","7","8","9"]','is_active'=>true,'is_featured'=>false,'sort_order'=>2,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>3,'category_id'=>1,'name'=>'Tranh Hoa Cúc Hồng H039','slug'=>'tranh-hoa-cuc-hong','description'=>'Tranh hoa cúc hồng (mã H039) – dịu dàng, lãng mạn. Khổ chuẩn 40×50cm, 24 màu.','image'=>'','price'=>199000,'color_count'=>,'size_ids'=>'["5","6","7","8","9"]','is_active'=>true,'is_featured'=>false,'sort_order'=>3,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>4,'category_id'=>1,'name'=>'Tranh Hoa Anh Đào H060','slug'=>'tranh-hoa-anh-dao-6a19ab6930795','description'=>'Tranh hoa đào & chim (mã H060) – nền xanh ngọc sang trọng, biểu tượng mùa xuân. Khổ chuẩn 40×50cm, 24 màu.','image'=>'','price'=>179000,'color_count'=>,'size_ids'=>'[]','is_active'=>true,'is_featured'=>false,'sort_order'=>4,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>5,'category_id'=>1,'name'=>'Tranh Hoa Mẫu Đơn H040','slug'=>'tranh-hoa-mau-don-6a19ab6944f21','description'=>'Tranh hoa mẫu đơn hồng trắng (mã H040) – tượng trưng phú quý, thịnh vượng. Khổ chuẩn 40×50cm, 24 màu.','image'=>'','price'=>199000,'color_count'=>,'size_ids'=>'["5","6","7","8","9"]','is_active'=>true,'is_featured'=>false,'sort_order'=>5,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>6,'category_id'=>1,'name'=>'Tranh Hoa Tulip Hà Lan H090','slug'=>'tranh-hoa-tulip-ha-lan-6a19ab695d961','description'=>'Tranh cánh đồng hoa tulip hoàng hôn (mã H090) – rực rỡ phong cách châu Âu. Khổ chuẩn 40×50cm, 24 màu.','image'=>'','price'=>159000,'color_count'=>,'size_ids'=>'["3","5","6","7","8","9"]','is_active'=>true,'is_featured'=>false,'sort_order'=>6,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>7,'category_id'=>2,'name'=>'Tranh Biển & Đồng Hoa C091','slug'=>'tranh-bien-dong-hoa-6a1a944f40d32','description'=>'Cô gái nằm giữa đồng hoa vàng bên bờ biển xanh – yên bình, thư thái.','image'=>'','price'=>159000,'color_count'=>,'size_ids'=>'["3","5","6","7","8","9"]','is_active'=>true,'is_featured'=>false,'sort_order'=>1,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>8,'category_id'=>2,'name'=>'Tranh Núi & Hươu Vàng D003','slug'=>'tranh-nui-huou-vang-6a1a944f5dda6','description'=>'Hươu vàng đứng trên đỉnh núi dưới ánh trăng – phong cách hiện đại, sang trọng.','image'=>'','price'=>199000,'color_count'=>,'size_ids'=>'["5","6","7","8","9"]','is_active'=>true,'is_featured'=>false,'sort_order'=>2,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>9,'category_id'=>3,'name'=>'Tranh Đôi Mèo Ban Công DV087','slug'=>'tranh-doi-meo-ban-cong-6a1a944f8eb1a','description'=>'Đôi mèo dễ thương tựa ban công ngắm phố – ấm áp, đáng yêu.','image'=>'','price'=>159000,'color_count'=>,'size_ids'=>'["3","5","6","7","8","9"]','is_active'=>true,'is_featured'=>false,'sort_order'=>3,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>10,'category_id'=>3,'name'=>'Tranh Gấu Trúc & Hoa DV089','slug'=>'tranh-gau-truc-hoa-6a1a944fa91ce','description'=>'Đàn gấu trúc baby ôm hoa đỏ – cực cute, hợp phòng trẻ em.','image'=>'','price'=>159000,'color_count'=>,'size_ids'=>'["3","5","6","7","8","9"]','is_active'=>true,'is_featured'=>false,'sort_order'=>4,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>11,'category_id'=>3,'name'=>'Tranh Mèo Lười Thư Giãn DV090','slug'=>'tranh-meo-luoi-thu-gian-6a1a944fc1898','description'=>'Bộ ba mèo béo nằm dài thư giãn – hài hước, vui nhộn.','image'=>'','price'=>159000,'color_count'=>,'size_ids'=>'["3","5","6","7","8","9"]','is_active'=>true,'is_featured'=>false,'sort_order'=>5,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>12,'category_id'=>2,'name'=>'Tranh Thuyền Buồm Hoàng Hôn B001','slug'=>'tranh-bien-b001-6a1afa4bc09a5','description'=>'Tranh Biển mã B001 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>100,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>13,'category_id'=>2,'name'=>'Tranh Hải Đăng Đêm Trăng B002','slug'=>'tranh-bien-b002-6a1afa4bdafd4','description'=>'Tranh Biển mã B002 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>101,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>14,'category_id'=>2,'name'=>'Tranh Thuyền Trên Vịnh Bình Yên B003','slug'=>'tranh-bien-b003-6a1afa4c02be5','description'=>'Tranh Biển mã B003 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>102,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>15,'category_id'=>2,'name'=>'Tranh Bãi Biển Mùa Hè B004','slug'=>'tranh-bien-b004-6a1afa4c1b26d','description'=>'Tranh Biển mã B004 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>103,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>16,'category_id'=>2,'name'=>'Tranh Sân Vườn Bên Biển B005','slug'=>'tranh-bien-b005-6a1afa4c3a7f4','description'=>'Tranh Biển mã B005 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>104,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>17,'category_id'=>2,'name'=>'Tranh Hoàng Hôn Trái Tim B006','slug'=>'tranh-bien-b006-6a1afa4c50e6d','description'=>'Tranh Biển mã B006 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>105,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>18,'category_id'=>2,'name'=>'Tranh Đêm Đèn Lồng Trên Biển B007','slug'=>'tranh-bien-b007-6a1afa4c674e8','description'=>'Tranh Biển mã B007 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>106,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>19,'category_id'=>2,'name'=>'Tranh Thuyền Vượt Sóng B008','slug'=>'tranh-bien-b008-6a1afa4c7fb03','description'=>'Tranh Biển mã B008 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>107,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>20,'category_id'=>2,'name'=>'Tranh Biển Vắng Võng Dừa C001','slug'=>'tranh-phong-canh-c001-6a1afa4c9801d','description'=>'Tranh Phong Cảnh mã C001 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>108,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>21,'category_id'=>2,'name'=>'Tranh Hươu Bên Suối Rừng C003','slug'=>'tranh-phong-canh-c003-6a1afa4cae73e','description'=>'Tranh Phong Cảnh mã C003 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>109,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>22,'category_id'=>2,'name'=>'Tranh Hồ Thu Bên Rừng Thông C004','slug'=>'tranh-phong-canh-c004-6a1afa4cc4e99','description'=>'Tranh Phong Cảnh mã C004 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>110,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>23,'category_id'=>2,'name'=>'Tranh Thuyền Bên Hồ Hoàng Hôn C005','slug'=>'tranh-phong-canh-c005-6a1afa4cdb38d','description'=>'Tranh Phong Cảnh mã C005 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>111,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>24,'category_id'=>2,'name'=>'Tranh Làng Biển Bình Yên C006','slug'=>'tranh-phong-canh-c006-6a1afa4d03897','description'=>'Tranh Phong Cảnh mã C006 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>112,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>25,'category_id'=>2,'name'=>'Tranh Đồng Lavender Khinh Khí Cầu C007','slug'=>'tranh-phong-canh-c007-6a1afa4d1bf20','description'=>'Tranh Phong Cảnh mã C007 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>113,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>26,'category_id'=>2,'name'=>'Tranh Hẹn Hò Mùa Hạ C008','slug'=>'tranh-phong-canh-c008-6a1afa4d324fc','description'=>'Tranh Phong Cảnh mã C008 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>114,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>27,'category_id'=>2,'name'=>'Tranh Làng Biển Ý Về Đêm C009','slug'=>'tranh-phong-canh-c009-6a1afa4d4abaf','description'=>'Tranh Phong Cảnh mã C009 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>115,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>28,'category_id'=>2,'name'=>'Tranh Nhà Gỗ Bên Hồ Hoàng Hôn C010','slug'=>'tranh-phong-canh-c010-6a1afa4d611f4','description'=>'Tranh Phong Cảnh mã C010 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>116,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>29,'category_id'=>2,'name'=>'Tranh Suối Núi Hoa Đỗ Quyên C011','slug'=>'tranh-phong-canh-c011-6a1afa4d77791','description'=>'Tranh Phong Cảnh mã C011 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>117,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>30,'category_id'=>2,'name'=>'Tranh Hoàng Hôn Mùa Đông C012','slug'=>'tranh-phong-canh-c012-6a1afa4d8fe3d','description'=>'Tranh Phong Cảnh mã C012 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>118,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>31,'category_id'=>2,'name'=>'Tranh Lễ Hội Khinh Khí Cầu C014','slug'=>'tranh-phong-canh-c014-6a1afa4da84bf','description'=>'Tranh Phong Cảnh mã C014 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>119,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>32,'category_id'=>2,'name'=>'Tranh Nhà Gỗ Đêm Trăng C015','slug'=>'tranh-phong-canh-c015-6a1afa4dc1e0d','description'=>'Tranh Phong Cảnh mã C015 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>120,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>33,'category_id'=>2,'name'=>'Tranh Vịnh Biển Địa Trung Hải C016','slug'=>'tranh-phong-canh-c016-6a1afa4dd920c','description'=>'Tranh Phong Cảnh mã C016 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>121,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>34,'category_id'=>2,'name'=>'Tranh Vịnh Portofino C017','slug'=>'tranh-phong-canh-c017-6a1afa4df3add','description'=>'Tranh Phong Cảnh mã C017 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>122,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>35,'category_id'=>2,'name'=>'Tranh Hải Đăng Bên Bờ Đá C019','slug'=>'tranh-phong-canh-c019-6a1afa4e19e68','description'=>'Tranh Phong Cảnh mã C019 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>123,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>36,'category_id'=>2,'name'=>'Tranh Cầu Đá Mùa Thu C020','slug'=>'tranh-phong-canh-c020-6a1afa4e32512','description'=>'Tranh Phong Cảnh mã C020 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>124,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>37,'category_id'=>2,'name'=>'Tranh Sân Vườn Bồ Câu C021','slug'=>'tranh-phong-canh-c021-6a1afa4e4beb4','description'=>'Tranh Phong Cảnh mã C021 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>125,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>38,'category_id'=>2,'name'=>'Tranh Bến Thuyền Venice C022','slug'=>'tranh-phong-canh-c022-6a1afa4e6444f','description'=>'Tranh Phong Cảnh mã C022 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>126,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>39,'category_id'=>2,'name'=>'Tranh Thác Nước Rừng Xanh C025','slug'=>'tranh-phong-canh-c025-6a1afa4e7d5fb','description'=>'Tranh Phong Cảnh mã C025 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>127,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>40,'category_id'=>2,'name'=>'Tranh Thác Núi Tuyết C026','slug'=>'tranh-phong-canh-c026-6a1afa4e96034','description'=>'Tranh Phong Cảnh mã C026 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>128,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>41,'category_id'=>2,'name'=>'Tranh Ngựa Bên Hồ Hoàng Hôn C027','slug'=>'tranh-phong-canh-c027-6a1afa4eae67c','description'=>'Tranh Phong Cảnh mã C027 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>129,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>42,'category_id'=>2,'name'=>'Tranh Cây Bốn Mùa C028','slug'=>'tranh-phong-canh-c028-6a1afa4ec7fea','description'=>'Tranh Phong Cảnh mã C028 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>130,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>43,'category_id'=>2,'name'=>'Tranh Cánh Đồng Tuscany C029','slug'=>'tranh-phong-canh-c029-6a1afa4ee14ba','description'=>'Tranh Phong Cảnh mã C029 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>131,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>44,'category_id'=>2,'name'=>'Tranh Hồ Liễu Rủ Hồng C030','slug'=>'tranh-phong-canh-c030-6a1afa4f099b0','description'=>'Tranh Phong Cảnh mã C030 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>132,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>45,'category_id'=>2,'name'=>'Tranh Nhà Bên Hồ Chiều Tà C031','slug'=>'tranh-phong-canh-c031-6a1afa4f213e4','description'=>'Tranh Phong Cảnh mã C031 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>133,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>46,'category_id'=>2,'name'=>'Tranh Vạn Lý Trường Thành C032','slug'=>'tranh-phong-canh-c032-6a1afa4f3baf1','description'=>'Tranh Phong Cảnh mã C032 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>134,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>47,'category_id'=>2,'name'=>'Tranh Hiên Nhà Gỗ Mùa Thu C033','slug'=>'tranh-phong-canh-c033-6a1afa4f5417a','description'=>'Tranh Phong Cảnh mã C033 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>135,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>48,'category_id'=>2,'name'=>'Tranh Thác Nước Thiên Nga C034','slug'=>'tranh-phong-canh-c034-6a1afa4f7099e','description'=>'Tranh Phong Cảnh mã C034 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>359000,'color_count'=>,'size_ids'=>'[10,11,12,13]','is_active'=>true,'is_featured'=>false,'sort_order'=>136,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>49,'category_id'=>2,'name'=>'Tranh Làng Chài Quán Cà Phê C035','slug'=>'tranh-phong-canh-c035-6a1afa4f88fdb','description'=>'Tranh Phong Cảnh mã C035 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>137,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>50,'category_id'=>2,'name'=>'Tranh Núi Phú Sĩ Hoa Anh Đào C036','slug'=>'tranh-phong-canh-c036-6a1afa4fa36fb','description'=>'Tranh Phong Cảnh mã C036 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>138,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>51,'category_id'=>2,'name'=>'Tranh Phố Cổ Bên Hồ Ý C037','slug'=>'tranh-phong-canh-c037-6a1afa4fbfec2','description'=>'Tranh Phong Cảnh mã C037 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>139,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>52,'category_id'=>2,'name'=>'Tranh Tháp Eiffel Trăng Tròn C038','slug'=>'tranh-phong-canh-c038-6a1afa4fd931d','description'=>'Tranh Phong Cảnh mã C038 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>359000,'color_count'=>,'size_ids'=>'[10,11]','is_active'=>true,'is_featured'=>false,'sort_order'=>140,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>53,'category_id'=>2,'name'=>'Tranh Phố Đồi Đà Lạt C039','slug'=>'tranh-phong-canh-c039-6a1afa5003815','description'=>'Tranh Phong Cảnh mã C039 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>141,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>54,'category_id'=>2,'name'=>'Tranh Làng Biển Nắng Ấm C040','slug'=>'tranh-phong-canh-c040-6a1afa501f26e','description'=>'Tranh Phong Cảnh mã C040 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>142,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>55,'category_id'=>2,'name'=>'Tranh Eiffel Mùa Thu C041','slug'=>'tranh-phong-canh-c041-6a1afa5038692','description'=>'Tranh Phong Cảnh mã C041 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>143,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>56,'category_id'=>2,'name'=>'Tranh Nhà Tranh Bên Suối Thu C042','slug'=>'tranh-phong-canh-c042-6a1afa5054177','description'=>'Tranh Phong Cảnh mã C042 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>144,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>57,'category_id'=>2,'name'=>'Tranh Đêm Đầy Sao Sông Rhône C043','slug'=>'tranh-phong-canh-c043-6a1afa506c810','description'=>'Tranh Phong Cảnh mã C043 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>145,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>58,'category_id'=>2,'name'=>'Tranh Nhà Đêm Trăng Bên Hồ C044','slug'=>'tranh-phong-canh-c044-6a1afa508f154','description'=>'Tranh Phong Cảnh mã C044 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>146,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>59,'category_id'=>2,'name'=>'Tranh Hệ Mặt Trời C045','slug'=>'tranh-phong-canh-c045-6a1afa50b7e47','description'=>'Tranh Phong Cảnh mã C045 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>147,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>60,'category_id'=>2,'name'=>'Tranh Đồng Quê Mùa Thu C046','slug'=>'tranh-phong-canh-c046-6a1afa50e07da','description'=>'Tranh Phong Cảnh mã C046 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>148,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>61,'category_id'=>2,'name'=>'Tranh Vịnh Làng Chài Ý C047','slug'=>'tranh-phong-canh-c047-6a1afa5108d43','description'=>'Tranh Phong Cảnh mã C047 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>149,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>62,'category_id'=>2,'name'=>'Tranh Đôi Chim Xanh Bên Hoa Hồng C048','slug'=>'tranh-phong-canh-c048-6a1afa51213b4','description'=>'Tranh Phong Cảnh mã C048 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>150,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>63,'category_id'=>2,'name'=>'Tranh Sơn Thủy Hữu Tình C049','slug'=>'tranh-phong-canh-c049-6a1afa513864e','description'=>'Tranh Phong Cảnh mã C049 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>469000,'color_count'=>,'size_ids'=>'[11,12,13,14]','is_active'=>true,'is_featured'=>false,'sort_order'=>151,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>64,'category_id'=>2,'name'=>'Tranh Sơn Thủy Tối Giản C050','slug'=>'tranh-phong-canh-c050-6a1afa5150173','description'=>'Tranh Phong Cảnh mã C050 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>152,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>65,'category_id'=>2,'name'=>'Tranh Đại Bàng Tung Cánh C051','slug'=>'tranh-phong-canh-c051-6a1afa516738a','description'=>'Tranh Phong Cảnh mã C051 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>153,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>66,'category_id'=>2,'name'=>'Tranh Ngôi Nhà Bóng Bay C052','slug'=>'tranh-phong-canh-c052-6a1afa517eca5','description'=>'Tranh Phong Cảnh mã C052 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>154,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>67,'category_id'=>2,'name'=>'Tranh Tiệm Sách Bên Biển C070','slug'=>'tranh-phong-canh-c070-6a1afa519731c','description'=>'Tranh Phong Cảnh mã C070 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>155,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>68,'category_id'=>2,'name'=>'Tranh Hoàng Hôn Cổ Tích C071','slug'=>'tranh-phong-canh-c071-6a1afa51ab8dc','description'=>'Tranh Phong Cảnh mã C071 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>156,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>69,'category_id'=>2,'name'=>'Tranh Xe Bus Hồng Bên Biển C072','slug'=>'tranh-phong-canh-c072-6a1afa51c2094','description'=>'Tranh Phong Cảnh mã C072 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>157,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>70,'category_id'=>2,'name'=>'Tranh Thị Trấn Kẹo Ngọt C075','slug'=>'tranh-phong-canh-c075-6a1afa51d6457','description'=>'Tranh Phong Cảnh mã C075 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>158,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>71,'category_id'=>2,'name'=>'Tranh Tiệm Hoa Gấu Con C076','slug'=>'tranh-phong-canh-c076-6a1afa51ef73b','description'=>'Tranh Phong Cảnh mã C076 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>159,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>72,'category_id'=>2,'name'=>'Tranh Tiệm Bánh Bao Gấu Trúc C077','slug'=>'tranh-phong-canh-c077-6a1afa5210f1a','description'=>'Tranh Phong Cảnh mã C077 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>160,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>73,'category_id'=>2,'name'=>'Tranh Phố Hội Cún Con C078','slug'=>'tranh-phong-canh-c078-6a1afa5226159','description'=>'Tranh Phong Cảnh mã C078 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>161,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>74,'category_id'=>2,'name'=>'Tranh Đại Dương Mèo Cún C079','slug'=>'tranh-phong-canh-c079-6a1afa523ba53','description'=>'Tranh Phong Cảnh mã C079 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>162,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>75,'category_id'=>2,'name'=>'Tranh Tiệm Kẹo Thỏ Hồng C080','slug'=>'tranh-phong-canh-c080-6a1afa5254214','description'=>'Tranh Phong Cảnh mã C080 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>163,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>76,'category_id'=>2,'name'=>'Tranh Nhà Nấm Mùa Thu C082','slug'=>'tranh-phong-canh-c082-6a1afa526c79d','description'=>'Tranh Phong Cảnh mã C082 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>164,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>77,'category_id'=>2,'name'=>'Tranh Kiệu Hoa Mèo Con C083','slug'=>'tranh-phong-canh-c083-6a1afa5284e7e','description'=>'Tranh Phong Cảnh mã C083 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>165,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>78,'category_id'=>2,'name'=>'Tranh Tiệm Trà Sữa Mèo C085','slug'=>'tranh-phong-canh-c085-6a1afa529f57f','description'=>'Tranh Phong Cảnh mã C085 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>166,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>79,'category_id'=>2,'name'=>'Tranh Nhà Cây Của Mèo C086','slug'=>'tranh-phong-canh-c086-6a1afa52b7bdd','description'=>'Tranh Phong Cảnh mã C086 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>167,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>80,'category_id'=>2,'name'=>'Tranh Xe Kem Thỏ Bông C087','slug'=>'tranh-phong-canh-c087-6a1afa52d2336','description'=>'Tranh Phong Cảnh mã C087 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>168,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>81,'category_id'=>2,'name'=>'Tranh Bé Gái Vườn Hoa C088','slug'=>'tranh-phong-canh-c088-6a1afa52e96a5','description'=>'Tranh Phong Cảnh mã C088 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>169,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>82,'category_id'=>2,'name'=>'Tranh Đèn Lồng Rồng Vàng C089','slug'=>'tranh-phong-canh-c089-6a1afa530ee36','description'=>'Tranh Phong Cảnh mã C089 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>170,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>83,'category_id'=>2,'name'=>'Tranh Biển Đêm Cuộn Sóng C090','slug'=>'tranh-phong-canh-c090-6a1afa5324108','description'=>'Tranh Phong Cảnh mã C090 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>171,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>84,'category_id'=>2,'name'=>'Tranh Gấu Trúc Đạp Xe C093','slug'=>'tranh-phong-canh-c093-6a1afa533b9f7','description'=>'Tranh Phong Cảnh mã C093 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>172,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>85,'category_id'=>2,'name'=>'Tranh Tiệm Mèo Dễ Thương C094','slug'=>'tranh-phong-canh-c094-6a1afa53540b1','description'=>'Tranh Phong Cảnh mã C094 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>173,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>86,'category_id'=>2,'name'=>'Tranh Rừng Thu Sơn Cước D001','slug'=>'tranh-trang-tri-d001-6a1afa536c794','description'=>'Tranh Trang Trí mã D001 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>174,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>87,'category_id'=>2,'name'=>'Tranh Bình Minh Trừu Tượng D002','slug'=>'tranh-trang-tri-d002-6a1afa5384f60','description'=>'Tranh Trang Trí mã D002 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>175,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>88,'category_id'=>2,'name'=>'Tranh Phố Cổ Châu Âu PH001','slug'=>'tranh-pho-ph001-6a1afa539d4ee','description'=>'Tranh Phố mã PH001 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>176,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>89,'category_id'=>2,'name'=>'Tranh Phố London Sôi Động PH002','slug'=>'tranh-pho-ph002-6a1afa53b3a9c','description'=>'Tranh Phố mã PH002 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>177,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>90,'category_id'=>2,'name'=>'Tranh Phố Đêm Xe Điện PH003','slug'=>'tranh-pho-ph003-6a1afa53ca103','description'=>'Tranh Phố mã PH003 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>178,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>91,'category_id'=>2,'name'=>'Tranh Phố London Tháp Đồng Hồ PH004','slug'=>'tranh-pho-ph004-6a1afa53e13b2','description'=>'Tranh Phố mã PH004 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>179,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>92,'category_id'=>2,'name'=>'Tranh Phố Amsterdam Về Đêm PH005','slug'=>'tranh-pho-ph005-6a1afa5404c37','description'=>'Tranh Phố mã PH005 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>180,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>93,'category_id'=>2,'name'=>'Tranh Ngõ Nhỏ Địa Trung Hải PH006','slug'=>'tranh-pho-ph006-6a1afa541dc88','description'=>'Tranh Phố mã PH006 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>181,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>94,'category_id'=>2,'name'=>'Tranh Phố Paris Hoa Lệ PH007','slug'=>'tranh-pho-ph007-6a1afa5437916','description'=>'Tranh Phố mã PH007 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>182,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>95,'category_id'=>2,'name'=>'Tranh Phố Thu Bên Sông PH008','slug'=>'tranh-pho-ph008-6a1afa545000f','description'=>'Tranh Phố mã PH008 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>183,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>96,'category_id'=>2,'name'=>'Tranh Venice Đêm Huyền Ảo PH009','slug'=>'tranh-pho-ph009-6a1afa5468643','description'=>'Tranh Phố mã PH009 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>184,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>97,'category_id'=>2,'name'=>'Tranh Bến Nước Venice PH010','slug'=>'tranh-pho-ph010-6a1afa5480d3b','description'=>'Tranh Phố mã PH010 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>185,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>98,'category_id'=>2,'name'=>'Tranh Venice Đèn Lồng Nổi PH011','slug'=>'tranh-pho-ph011-6a1afa549b448','description'=>'Tranh Phố mã PH011 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>186,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>99,'category_id'=>2,'name'=>'Tranh Phố Đèn Lồng Đỏ PH012','slug'=>'tranh-pho-ph012-6a1afa54b3b0f','description'=>'Tranh Phố mã PH012 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>187,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>100,'category_id'=>2,'name'=>'Tranh Phố Mưa Châu Âu PH013','slug'=>'tranh-pho-ph013-6a1afa54ce227','description'=>'Tranh Phố mã PH013 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>188,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>101,'category_id'=>2,'name'=>'Tranh Ngõ Nước Venice PH014','slug'=>'tranh-pho-ph014-6a1afa54e5555','description'=>'Tranh Phố mã PH014 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>189,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>102,'category_id'=>2,'name'=>'Tranh Phố Đêm Montmartre PH015','slug'=>'tranh-pho-ph015-6a1afa550ace4','description'=>'Tranh Phố mã PH015 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>190,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>103,'category_id'=>2,'name'=>'Tranh Venice Đêm Vàng PH016','slug'=>'tranh-pho-ph016-6a1afa5523381','description'=>'Tranh Phố mã PH016 – tranh tô màu số hóa DALI, khổ 40×50cm đã căng khung.','image'=>'','price'=>169000,'color_count'=>,'size_ids'=>'[3,5,6,7,8,9]','is_active'=>true,'is_featured'=>false,'sort_order'=>191,'sold_count'=>0,'created_at'=>$now,'updated_at'=>$now],
        ]);

        // ── Cộng tác viên ──
        DB::table('affiliates')->truncate();
        DB::table('affiliates')->insert([
            ['name'=>'CTV Demo','phone'=>'0900000001','email'=>'','code'=>'DALI_DEMO','password'=>'$2y$12$EHewc5PCzthEutbLKpSyo.mkvtbwSwb7njquH9/qEhWvryRIhxGAy','commission_rate'=>20,'total_earned'=>0,'total_paid'=>0,'total_orders'=>0,'bank_name'=>'Vietcombank','bank_acc'=>'0123456789','bank_owner'=>'CTV DEMO','is_active'=>true,'note'=>'','created_at'=>$now,'updated_at'=>$now],
        ]);
    }
}
