# Generated by Django 4.1.2 on 2022-11-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_imagemodel_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='colors',
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='image_output',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
