# Generated by Django 4.1.2 on 2022-11-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_imagemodel_colors_imagemodel_image_output_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='name_output',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
