# Generated by Django 4.1.2 on 2022-11-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_imagemodel_name_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='colors',
            field=models.JSONField(max_length=250),
        ),
    ]
