# Generated by Django 4.1.2 on 2022-11-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_imagemodel_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='colors',
            field=models.TextField(max_length=250),
        ),
    ]
