# Generated by Django 4.1.2 on 2022-11-07 02:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_imagemodel_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
