# Generated by Django 4.1.2 on 2026-06-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_imagemodel_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='status',
            field=models.CharField(default='done', max_length=20),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='colors',
            field=models.JSONField(blank=True, default=list, max_length=250),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image_output',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='name_output',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
    ]
